name-template: 'v$NEXT_PATCH_VERSION 🌟'
tag-template: 'v$NEXT_PATCH_VERSION'

categories:
  - title: '🚀 Features'
    labels:
      - 'feature'

  - title: '🐛 Bug Fixes'
    labels:
      - 'fix'

  - title: '🔒 Dependencies'
    labels:
      - 'dependencies'

change-template: |
  - $TITLE @$AUTHOR (#$NUMBER)
    $BODY

no-changes-template: '- No user-facing changes in this release.'

replacers:
  - search: '- [ ] The corresponding ticket is in state `In Review`'
    replace: ''
  - search: '- [x] The corresponding ticket is in state `In Review`'
    replace: ''
  - search: '- [ ] The corresponding ticket is attached to this Pull-Request'
    replace: ''
  - search: '- [x] The corresponding ticket is attached to this Pull-Request'
    replace: ''
  - search: '- [ ] The commit-message-format `Closes #ISSUE_ID - PROBLEM/SOLUTION`'
    replace: ''
  - search: '- [x] The commit-message-format `Closes #ISSUE_ID - PROBLEM/SOLUTION`'
    replace: ''
  - search: '  - is present as single-commit already or'
    replace: ''
  - search: '  - will be squashed on merge'
    replace: ''
  - search: '- [ ] The changes pass the SonarQubeCloud-Quality-Gate'
    replace: ''
  - search: '- [x] The changes pass the SonarQubeCloud-Quality-Gate'
    replace: ''
  - search: '- [ ] If the documentation needs an update, following there is a link to it:'
    replace: ''
  - search: '- [x] If the documentation needs an update, following there is a link to it:'
    replace: ''
  - search: '## Definition of Done'
    replace: ''
  - search: '## Custom Release-Notes'
    replace: ''
template: |
  ## 📦 Release Notes

  $CHANGES

  **Full Changelog**: https://github.com/$OWNER/$REPOSITORY/compare/$PREVIOUS_TAG...$TAG
