name-template: 'v$NEXT_PATCH_VERSION 🌟'
tag-template: 'v$NEXT_PATCH_VERSION'

categories:
  - title: '🚀 Feature'
    labels:
      - 'feature'
    change-template: |
      - $BODY

  - title: '🐛 Bug Fixes'
    labels:
      - 'fix'
    change-template: |
      - $BODY

  - title: '🔒 Dependencies'
    labels:
      - 'dependencies'
    change-template: '- $TITLE @$AUTHOR (#$NUMBER)'

  - title: '📦 What’s Changed?'
    labels:
      - '*'
    exclude-labels:
      - 'feature'
      - 'fix'
      - 'dependencies'
    change-template: |
      - $BODY

no-changes-template: '- No user-facing changes in this release.'

template: |
  ## 📦 Release Notes

  $CHANGES

  **Full Changelog**: https://github.com/$OWNER/$REPOSITORY/compare/$PREVIOUS_TAG...$TAG