name: Postprocess Release Notes

on:
  release:
    types: [created, edited]

permissions:
  contents: write

jobs:
  postprocess:
    if: ${{ github.event.release.draft }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Haskell
        uses: haskell/actions/setup@v2
        with:
          ghc-version: "9.10.1"
          cabal-version: "3.14.2.0"

      - name: Build Haskell tool
        run: |
          cabal update
          cabal build exe:release-notes-postprocessor
          cp $(cabal list-bin exe:release-notes-postprocessor) ./release-notes-postprocessor

      - name: Save current release notes
        run: |
          echo "${{ github.event.release.body }}" > original.md

      - name: Run postprocessor
        run: |
          ./release-notes-postprocessor < original.md > processed.md

      - name: Update release with processed notes
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const newBody = fs.readFileSync('processed.md', 'utf8');
            await github.rest.repos.updateRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
              release_id: context.payload.release.id,
              body: newBody
            });
